//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookingRecreation
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Application user.
    /// </summary>
    //  *** Start programmer edit section *** (ApplicationUser CustomAttributes)

    //  *** End programmer edit section *** (ApplicationUser CustomAttributes)
    [PublishName("ApplicationUser")]
    [AutoAltered()]
    [Caption("Пользователь приложения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ApplicationUserE", new string[] {
            "Phone as \'Phone\'",
            "Email as \'Email\'",
            "IsAdmin as \'Is admin\'",
            "Name as \'Name\'"})]
    [View("ApplicationUserL", new string[] {
            "Phone as \'Phone\'",
            "Email as \'Email\'",
            "IsAdmin as \'Is admin\'",
            "Name as \'Name\'"})]
    public class ApplicationUser : ICSSoft.STORMNET.DataObject
    {
        
        private string fPhone;
        
        private string fEmail;
        
        private bool fIsAdmin = false;
        
        private string fName;
        
        //  *** Start programmer edit section *** (ApplicationUser CustomMembers)

        //  *** End programmer edit section *** (ApplicationUser CustomMembers)

        
        /// <summary>
        /// Phone.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.Phone CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.Phone CustomAttributes)
        [StrLen(255)]
        public virtual string Phone
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.Phone Get start)

                //  *** End programmer edit section *** (ApplicationUser.Phone Get start)
                string result = this.fPhone;
                //  *** Start programmer edit section *** (ApplicationUser.Phone Get end)

                //  *** End programmer edit section *** (ApplicationUser.Phone Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.Phone Set start)

                //  *** End programmer edit section *** (ApplicationUser.Phone Set start)
                this.fPhone = value;
                //  *** Start programmer edit section *** (ApplicationUser.Phone Set end)

                //  *** End programmer edit section *** (ApplicationUser.Phone Set end)
            }
        }
        
        /// <summary>
        /// Email.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.Email CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.Email Get start)

                //  *** End programmer edit section *** (ApplicationUser.Email Get start)
                string result = this.fEmail;
                //  *** Start programmer edit section *** (ApplicationUser.Email Get end)

                //  *** End programmer edit section *** (ApplicationUser.Email Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.Email Set start)

                //  *** End programmer edit section *** (ApplicationUser.Email Set start)
                this.fEmail = value;
                //  *** Start programmer edit section *** (ApplicationUser.Email Set end)

                //  *** End programmer edit section *** (ApplicationUser.Email Set end)
            }
        }
        
        /// <summary>
        /// IsAdmin.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.IsAdmin CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.IsAdmin CustomAttributes)
        public virtual bool IsAdmin
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Get start)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Get start)
                bool result = this.fIsAdmin;
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Get end)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Set start)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Set start)
                this.fIsAdmin = value;
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Set end)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.Name CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.Name Get start)

                //  *** End programmer edit section *** (ApplicationUser.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (ApplicationUser.Name Get end)

                //  *** End programmer edit section *** (ApplicationUser.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.Name Set start)

                //  *** End programmer edit section *** (ApplicationUser.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (ApplicationUser.Name Set end)

                //  *** End programmer edit section *** (ApplicationUser.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ApplicationUserE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationUserE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationUserE", typeof(IIS.BookingRecreation.ApplicationUser));
                }
            }
            
            /// <summary>
            /// "ApplicationUserL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationUserL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationUserL", typeof(IIS.BookingRecreation.ApplicationUser));
                }
            }
        }
    }
}
