//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookingRecreation
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Recreation.
    /// </summary>
    //  *** Start programmer edit section *** (Recreation CustomAttributes)

    //  *** End programmer edit section *** (Recreation CustomAttributes)
    [PublishName("Recreation")]
    [AutoAltered()]
    [Caption("База отдыха")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RecreationE", new string[] {
            "Phone as \'Phone\'",
            "Address as \'Address\'",
            "Name as \'Name\'"})]
    [AssociatedDetailViewAttribute("RecreationE", "Employees", "RecreationEmployeeE", true, "", "Employees", true, new string[] {
            ""})]
    [View("RecreationL", new string[] {
            "Phone as \'Phone\'",
            "Address as \'Address\'",
            "Name as \'Name\'"})]
    public class Recreation : ICSSoft.STORMNET.DataObject
    {
        
        private string fPhone;
        
        private string fAddress;
        
        private string fName;
        
        private IIS.BookingRecreation.DetailArrayOfRecreationEmployee fEmployees;
        
        //  *** Start programmer edit section *** (Recreation CustomMembers)

        //  *** End programmer edit section *** (Recreation CustomMembers)

        
        /// <summary>
        /// Phone.
        /// </summary>
        //  *** Start programmer edit section *** (Recreation.Phone CustomAttributes)

        //  *** End programmer edit section *** (Recreation.Phone CustomAttributes)
        [StrLen(255)]
        public virtual string Phone
        {
            get
            {
                //  *** Start programmer edit section *** (Recreation.Phone Get start)

                //  *** End programmer edit section *** (Recreation.Phone Get start)
                string result = this.fPhone;
                //  *** Start programmer edit section *** (Recreation.Phone Get end)

                //  *** End programmer edit section *** (Recreation.Phone Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Recreation.Phone Set start)

                //  *** End programmer edit section *** (Recreation.Phone Set start)
                this.fPhone = value;
                //  *** Start programmer edit section *** (Recreation.Phone Set end)

                //  *** End programmer edit section *** (Recreation.Phone Set end)
            }
        }
        
        /// <summary>
        /// Address.
        /// </summary>
        //  *** Start programmer edit section *** (Recreation.Address CustomAttributes)

        //  *** End programmer edit section *** (Recreation.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                //  *** Start programmer edit section *** (Recreation.Address Get start)

                //  *** End programmer edit section *** (Recreation.Address Get start)
                string result = this.fAddress;
                //  *** Start programmer edit section *** (Recreation.Address Get end)

                //  *** End programmer edit section *** (Recreation.Address Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Recreation.Address Set start)

                //  *** End programmer edit section *** (Recreation.Address Set start)
                this.fAddress = value;
                //  *** Start programmer edit section *** (Recreation.Address Set end)

                //  *** End programmer edit section *** (Recreation.Address Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Recreation.Name CustomAttributes)

        //  *** End programmer edit section *** (Recreation.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Recreation.Name Get start)

                //  *** End programmer edit section *** (Recreation.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Recreation.Name Get end)

                //  *** End programmer edit section *** (Recreation.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Recreation.Name Set start)

                //  *** End programmer edit section *** (Recreation.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Recreation.Name Set end)

                //  *** End programmer edit section *** (Recreation.Name Set end)
            }
        }
        
        /// <summary>
        /// Recreation.
        /// </summary>
        //  *** Start programmer edit section *** (Recreation.Employees CustomAttributes)

        //  *** End programmer edit section *** (Recreation.Employees CustomAttributes)
        public virtual IIS.BookingRecreation.DetailArrayOfRecreationEmployee Employees
        {
            get
            {
                //  *** Start programmer edit section *** (Recreation.Employees Get start)

                //  *** End programmer edit section *** (Recreation.Employees Get start)
                if ((this.fEmployees == null))
                {
                    this.fEmployees = new IIS.BookingRecreation.DetailArrayOfRecreationEmployee(this);
                }
                IIS.BookingRecreation.DetailArrayOfRecreationEmployee result = this.fEmployees;
                //  *** Start programmer edit section *** (Recreation.Employees Get end)

                //  *** End programmer edit section *** (Recreation.Employees Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Recreation.Employees Set start)

                //  *** End programmer edit section *** (Recreation.Employees Set start)
                this.fEmployees = value;
                //  *** Start programmer edit section *** (Recreation.Employees Set end)

                //  *** End programmer edit section *** (Recreation.Employees Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RecreationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RecreationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RecreationE", typeof(IIS.BookingRecreation.Recreation));
                }
            }
            
            /// <summary>
            /// "RecreationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RecreationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RecreationL", typeof(IIS.BookingRecreation.Recreation));
                }
            }
        }
    }
}
