//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookingRecreation
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Recreation employee.
    /// </summary>
    //  *** Start programmer edit section *** (RecreationEmployee CustomAttributes)

    //  *** End programmer edit section *** (RecreationEmployee CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудник базы отдыха")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RecreationEmployeeE", new string[] {
            "RecreationAdmin as \'Recreation admin\'",
            "User as \'User\'",
            "User.Phone as \'Phone\'"}, Hidden=new string[] {
            "User.Phone"})]
    [MasterViewDefineAttribute("RecreationEmployeeE", "User", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Phone")]
    public class RecreationEmployee : ICSSoft.STORMNET.DataObject
    {
        
        private bool fRecreationAdmin = false;
        
        private IIS.BookingRecreation.ApplicationUser fUser;
        
        private IIS.BookingRecreation.Recreation fRecreation;
        
        //  *** Start programmer edit section *** (RecreationEmployee CustomMembers)

        //  *** End programmer edit section *** (RecreationEmployee CustomMembers)

        
        /// <summary>
        /// RecreationAdmin.
        /// </summary>
        //  *** Start programmer edit section *** (RecreationEmployee.RecreationAdmin CustomAttributes)

        //  *** End programmer edit section *** (RecreationEmployee.RecreationAdmin CustomAttributes)
        public virtual bool RecreationAdmin
        {
            get
            {
                //  *** Start programmer edit section *** (RecreationEmployee.RecreationAdmin Get start)

                //  *** End programmer edit section *** (RecreationEmployee.RecreationAdmin Get start)
                bool result = this.fRecreationAdmin;
                //  *** Start programmer edit section *** (RecreationEmployee.RecreationAdmin Get end)

                //  *** End programmer edit section *** (RecreationEmployee.RecreationAdmin Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (RecreationEmployee.RecreationAdmin Set start)

                //  *** End programmer edit section *** (RecreationEmployee.RecreationAdmin Set start)
                this.fRecreationAdmin = value;
                //  *** Start programmer edit section *** (RecreationEmployee.RecreationAdmin Set end)

                //  *** End programmer edit section *** (RecreationEmployee.RecreationAdmin Set end)
            }
        }
        
        /// <summary>
        /// Recreation employee.
        /// </summary>
        //  *** Start programmer edit section *** (RecreationEmployee.User CustomAttributes)

        //  *** End programmer edit section *** (RecreationEmployee.User CustomAttributes)
        [NotNull()]
        public virtual IIS.BookingRecreation.ApplicationUser User
        {
            get
            {
                //  *** Start programmer edit section *** (RecreationEmployee.User Get start)

                //  *** End programmer edit section *** (RecreationEmployee.User Get start)
                IIS.BookingRecreation.ApplicationUser result = this.fUser;
                //  *** Start programmer edit section *** (RecreationEmployee.User Get end)

                //  *** End programmer edit section *** (RecreationEmployee.User Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (RecreationEmployee.User Set start)

                //  *** End programmer edit section *** (RecreationEmployee.User Set start)
                this.fUser = value;
                //  *** Start programmer edit section *** (RecreationEmployee.User Set end)

                //  *** End programmer edit section *** (RecreationEmployee.User Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.BookingRecreation.Recreation.
        /// </summary>
        //  *** Start programmer edit section *** (RecreationEmployee.Recreation CustomAttributes)

        //  *** End programmer edit section *** (RecreationEmployee.Recreation CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.BookingRecreation.Recreation Recreation
        {
            get
            {
                //  *** Start programmer edit section *** (RecreationEmployee.Recreation Get start)

                //  *** End programmer edit section *** (RecreationEmployee.Recreation Get start)
                IIS.BookingRecreation.Recreation result = this.fRecreation;
                //  *** Start programmer edit section *** (RecreationEmployee.Recreation Get end)

                //  *** End programmer edit section *** (RecreationEmployee.Recreation Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (RecreationEmployee.Recreation Set start)

                //  *** End programmer edit section *** (RecreationEmployee.Recreation Set start)
                this.fRecreation = value;
                //  *** Start programmer edit section *** (RecreationEmployee.Recreation Set end)

                //  *** End programmer edit section *** (RecreationEmployee.Recreation Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RecreationEmployeeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RecreationEmployeeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RecreationEmployeeE", typeof(IIS.BookingRecreation.RecreationEmployee));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of RecreationEmployee.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfRecreationEmployee CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfRecreationEmployee CustomAttributes)
    public class DetailArrayOfRecreationEmployee : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.BookingRecreation.DetailArrayOfRecreationEmployee members)

        //  *** End programmer edit section *** (IIS.BookingRecreation.DetailArrayOfRecreationEmployee members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type RecreationEmployee by index.
        /// </summary>
        /// <summary>
        /// Adds object with type RecreationEmployee.
        /// </summary>
        public DetailArrayOfRecreationEmployee(IIS.BookingRecreation.Recreation fRecreation) : 
                base(typeof(RecreationEmployee), ((ICSSoft.STORMNET.DataObject)(fRecreation)))
        {
        }
        
        public IIS.BookingRecreation.RecreationEmployee this[int index]
        {
            get
            {
                return ((IIS.BookingRecreation.RecreationEmployee)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.BookingRecreation.RecreationEmployee dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
